"""Create Person, GuessedWord and Theme Tables

Revision ID: 8c0163e8866c
Revises: 
Create Date: 2024-05-09 14:34:19.495630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0163e8866c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_salt_hash', sa.String(length=128), nullable=False),
    sa.Column('salt', sa.String(length=16), nullable=False),
    sa.Column('win_total', sa.Integer(), nullable=True),
    sa.Column('loss_total', sa.Integer(), nullable=True),
    sa.Column('points_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('guessed_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('guessed_word', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=12), nullable=False),
    sa.Column('word1', sa.String(length=12), nullable=False),
    sa.Column('word2', sa.String(length=12), nullable=False),
    sa.Column('word3', sa.String(length=12), nullable=False),
    sa.Column('word4', sa.String(length=12), nullable=False),
    sa.Column('word5', sa.String(length=12), nullable=False),
    sa.Column('word6', sa.String(length=12), nullable=False),
    sa.Column('word7', sa.String(length=12), nullable=False),
    sa.Column('word8', sa.String(length=12), nullable=False),
    sa.Column('word9', sa.String(length=12), nullable=False),
    sa.Column('word10', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theme')
    op.drop_table('guessed_word')
    op.drop_table('person')
    # ### end Alembic commands ###
